name: hello-world
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs: 
  print-hello-world: 
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "Hello World"
      - run: ls -l

  install-dependencies:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm test

  build-image:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.actor }}/subject-api
        tags: |
          type=sha
        flavor: |
          latest=${{ github.event_name == 'push' }}

    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
